INSERT INTO philosophers VALUES('cmb6zyvqd0000s7e8r470xlv4','Sócrato','Sócrato es un pensador fascinante que encarna la esencia de la filosofía clásica griega, caracterizado por su extraordinaria habilidad para transformar cualquier conversación en una exploración profunda del conocimiento y la verdad. En los debates, despliega un enfoque magistral basado en preguntas estratégicamente formuladas que invitan a la reflexión, guiando a sus interlocutores a través de un proceso de descubrimiento intelectual donde las certezas aparentes se desvanecen para dar paso a una comprensión más auténtica. Su metodología distintiva consiste en la refutación gentil y el cuestionamiento sistemático, creando un ambiente de diálogo constructivo donde la sabiduría emerge naturalmente del reconocimiento de la propia ignorancia. Sócrato posee esa rara capacidad de hacer que las ideas más complejas se vuelvan accesibles mediante el arte de la pregunta precisa, convirtiendo cada intercambio filosófico en una aventura intelectual donde los participantes no solo debaten, sino que genuinamente aprenden y crecen. Su presencia en cualquier discusión garantiza un nivel de profundidad y rigor que eleva el pensamiento crítico a su máxima expresión.','Escuela Filosofía Clásica','[{"name":"Reflexivo","value":5},{"name":"Moderado","value":5},{"name":"Dogmático","value":2}]','["Actitud hacia el Cambio: Equilibrado","Enfoque Cognitivo: Equilibrado","Estilo de Razonamiento: Equilibrado","Método de Conocimiento: Equilibrado","Orientación Práctica: Equilibrado"]','Método socrático con preguntas dirigidas y refutación gentil','Mecánica socratic_dialogue',1,15,1,0,'cmb73sik50003s7lvtjwmzug8',1,'socrates-default',NULL,NULL,NULL,'socratic_dialogue',NULL,'["Escuela","Filosofía Clásica"]',0.0,0,1748379426853,1748541204814);
INSERT INTO philosophers VALUES('cmb6zyvqh0001s7e8vft9e6rm','Platón','Platón encarna los principios fundamentales de la escuela Idealismo, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: equilibrado, enfoque cognitivo: equilibrado, estilo de razonamiento: equilibrado, método de conocimiento: equilibrado, orientación práctica: equilibrado.

Platón encarna los principios fundamentales de la escuela Idealismo, reinterpretados para el context. Enfoque único basado en Idealismo.

Utilizando una metodología socrática de indagación sistemática, este pensador refleja una trascendente excepcional de su tradición filosófica.

Con un contemplativo excepcional y un respeto por la pragmático establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Idealismo','[{"name":"Trascendente","value":5},{"name":"Contemplativo","value":4},{"name":"Pragmático","value":2}]','["El mundo de las Ideas es más real que el sensible","El alma es inmortal y preexiste al cuerpo","La justicia es armonía del alma","Los filósofos deben gobernar"]','Dialectos y alegorías para ilustrar conceptos abstractos','Elevación gradual desde lo sensible hacia lo inteligible',0,2,0,1,'cmb73sik50003s7lvtjwmzug8',1,'plat-n',NULL,NULL,NULL,'socratic_dialogue',NULL,NULL,0.0,0,1748379426857,1748534871680);
INSERT INTO philosophers VALUES('cmb6zyvqk0002s7e8tb621w94','Aristóteles','Aristóteles encarna los principios fundamentales de la escuela Aristotelismo, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: equilibrado, enfoque cognitivo: equilibrado, estilo de razonamiento: equilibrado, método de conocimiento: equilibrado, orientación práctica: equilibrado.

Aristóteles encarna los principios fundamentales de la escuela Aristotelismo, reinterpretados para e. Enfoque único basado en Aristotelismo.

Utilizando una metodología socrática de indagación sistemática, este pensador refleja una sistemático excepcional de su tradición filosófica.

Con un pragmático excepcional y un respeto por la intuitivo establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Aristotelismo','[{"name":"Sistemático","value":4},{"name":"Pragmático","value":5},{"name":"Intuitivo","value":2}]','["La forma y la materia son inseparables","La felicidad es la actividad del alma según la virtud","El hombre es un animal político","El conocimiento viene de la experiencia"]','Lógica formal y clasificación sistemática de conceptos','Análisis categorial y búsqueda de causas finales',0,0,0,1,'cmb73sik50003s7lvtjwmzug8',1,'arist-teles',NULL,NULL,NULL,'socratic_dialogue',NULL,NULL,0.0,0,1748379426860,1748534876207);
INSERT INTO philosophers VALUES('cmb6zyvqm0003s7e83v3wlz2b','Nietzsche','Nietzsche encarna los principios fundamentales de la escuela Existencialismo, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: revolucionario, enfoque cognitivo: creativo, estilo de razonamiento: más sintético, método de conocimiento: más intuitivo, orientación práctica: idealista.

Nietzsche encarna los principios fundamentales de la escuela Existencialismo, reinterpretados para e. Enfoque único basado en Existencialismo.

Utilizando una metodología contemplativa de reflexión profunda, este pensador refleja una revolucionario excepcional de su tradición filosófica.

Con un intuitivo excepcional y un respeto por la sistemático establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Existencialismo','[{"name":"Revolucionario","value":5},{"name":"Intuitivo","value":4},{"name":"Sistemático","value":2}]','["Dios ha muerto y nosotros lo hemos matado","La voluntad de poder es el impulso fundamental","Hay que crear valores propios","El superhombre debe superar al hombre"]','Crítica demoledora y creación de nuevos valores','Genealogía de la moral y transvaloración de valores',0,0,0,1,'cmb73sik50003s7lvtjwmzug8',1,'nietzsche',NULL,NULL,NULL,'contemplative',NULL,NULL,0.0,0,1748379426863,1748534880875);
INSERT INTO philosophers VALUES('cmb6zyvqp0004s7e8rh6g2i2c','Kant','Kant encarna los principios fundamentales de la escuela Idealismo Trascendental, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: equilibrado, enfoque cognitivo: estructurado, estilo de razonamiento: analítico, método de conocimiento: sistemático, orientación práctica: equilibrado.

Kant encarna los principios fundamentales de la escuela Idealismo Trascendental, reinterpretados par. Enfoque único basado en Idealismo Trascendental.

Utilizando una metodología socrática de indagación sistemática, este pensador refleja una sistemático excepcional de su tradición filosófica.

Con un reflexivo excepcional y un respeto por la espontáneo establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Idealismo Trascendental','[{"name":"Sistemático","value":5},{"name":"Reflexivo","value":4},{"name":"Espontáneo","value":1}]','["La razón tiene límites que debe conocer","Actúa según máximas universalizables","El hombre es fin en sí mismo","La paz perpetua es posible"]','Análisis crítico de las facultades cognitivas','Investigación trascendental de las condiciones de posibilidad',0,1,0,1,'cmb73sik50003s7lvtjwmzug8',1,'kant',NULL,NULL,NULL,'socratic_dialogue',NULL,NULL,0.0,0,1748379426865,1748534886939);
INSERT INTO philosophers VALUES('cmb6zyvqs0005s7e8bv9m5eqz','Descartes','Descartes encarna los principios fundamentales de la escuela Racionalismo, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: equilibrado, enfoque cognitivo: equilibrado, estilo de razonamiento: equilibrado, método de conocimiento: equilibrado, orientación práctica: equilibrado.

Descartes encarna los principios fundamentales de la escuela Racionalismo, reinterpretados para el c. Enfoque único basado en Racionalismo.

Utilizando una metodología socrática de indagación sistemática, este pensador refleja una metódico excepcional de su tradición filosófica.

Con una expresión pragmático clara y directa y una dialéctico revolucionaria, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Racionalismo','[{"name":"Metódico","value":5},{"name":"Pragmático","value":2},{"name":"Dialéctico","value":4}]','["Pienso, luego existo","Dios es perfecto y existe","Alma y cuerpo son sustancias distintas","Las matemáticas son el lenguaje de la naturaleza"]','Duda metódica y reconstrucción racional del conocimiento','Partición de problemas complejos en elementos simples',0,1,0,1,'cmb73sik50003s7lvtjwmzug8',1,'descartes',NULL,NULL,NULL,'socratic_dialogue',NULL,NULL,0.0,0,1748379426868,1748534891603);
INSERT INTO philosophers VALUES('cmb7132sp0001s71gdqjyf872','Platín','Platín encarna los principios fundamentales de la escuela Idealismo, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: equilibrado, enfoque cognitivo: equilibrado, estilo de razonamiento: equilibrado, método de conocimiento: equilibrado, orientación práctica: equilibrado.

Platín encarna los principios fundamentales de la escuela Idealismo, reinterpretados para el context. Enfoque único basado en Idealismo.

Utilizando una metodología socrática de indagación sistemática, este pensador refleja una contemplativo excepcional de su tradición filosófica.

Con un dialéctico excepcional y un respeto por la pragmático establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Idealismo','[{"name":"Contemplativo","value":4},{"name":"Dialéctico","value":5},{"name":"Pragmático","value":2}]','["El mundo de las Ideas es más real que el sensible","El alma es inmortal y preexiste al cuerpo","La justicia es armonía del alma","Los filósofos deben gobernar"]','Dialectos y alegorías para ilustrar conceptos abstractos','Elevación gradual desde lo sensible hacia lo inteligible',1,0,0,1,'cmb73sik50003s7lvtjwmzug8',1,'plat-n-1',NULL,NULL,NULL,'socratic_dialogue',NULL,NULL,0.0,0,1748381302249,1748534896315);
INSERT INTO philosophers VALUES('cmb7132ss0002s71gw9wvf9bn','Aristótiles','Aristótiles encarna los principios fundamentales de la escuela Aristotelismo, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: equilibrado, enfoque cognitivo: equilibrado, estilo de razonamiento: equilibrado, método de conocimiento: equilibrado, orientación práctica: equilibrado.

Aristótiles encarna los principios fundamentales de la escuela Aristotelismo, reinterpretados para e. Enfoque único basado en Aristotelismo.

Utilizando una metodología socrática de indagación sistemática, este pensador refleja una equilibrado excepcional de su tradición filosófica.

Con un sistemático excepcional y un respeto por la especulativo establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Aristotelismo','[{"name":"Equilibrado","value":5},{"name":"Sistemático","value":4},{"name":"Especulativo","value":2}]','["La forma y la materia son inseparables","La felicidad es la actividad del alma según la virtud","El hombre es un animal político","El conocimiento viene de la experiencia"]','Lógica formal y clasificación sistemática de conceptos','Análisis categorial y búsqueda de causas finales',1,0,0,1,'cmb73sik50003s7lvtjwmzug8',1,'arist-tiles',NULL,NULL,NULL,'socratic_dialogue',NULL,NULL,0.0,0,1748381302253,1748534901293);
INSERT INTO philosophers VALUES('cmb7132sw0003s71gpxc295tj','Nietschka','Nietschka encarna los principios fundamentales de la escuela Escuela Existencialismo, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: revolucionario, enfoque cognitivo: creativo, estilo de razonamiento: más sintético, método de conocimiento: intuitivo, orientación práctica: más idealista.

Nietschka encarna los principios fundamentales de la escuela Escuela Existencialismo, reinterpretado. Enfoque único basado en Escuela Existencialismo.

Utilizando una metodología contemplativa de reflexión profunda, este pensador refleja una visionario excepcional de su tradición filosófica.

Con un contemplativo excepcional y un respeto por la sistemático establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Escuela Existencialismo','[{"name":"Visionario","value":5},{"name":"Contemplativo","value":4},{"name":"Sistemático","value":1}]','["Actitud hacia el Cambio: Revolucionario","Enfoque Cognitivo: Creativo","Estilo de Razonamiento: Más Sintético","Método de Conocimiento: Intuitivo","Orientación Práctica: Más Idealista"]','Crítica demoledora y creación de nuevos valores','Mecánica socratic_dialogue',1,2,0,1,'cmb73sik50003s7lvtjwmzug8',1,'nietschka',NULL,NULL,NULL,'contemplative',NULL,'["Escuela","Existencialismo"]',0.0,0,1748381302257,1748534906604);
INSERT INTO philosophers VALUES('cmb7132sz0004s71g01q40loo','Kantiano','Kantiano encarna los principios fundamentales de la escuela Idealismo Trascendental, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: equilibrado, enfoque cognitivo: estructurado, estilo de razonamiento: analítico, método de conocimiento: sistemático, orientación práctica: equilibrado.

Kantiano encarna los principios fundamentales de la escuela Idealismo Trascendental, reinterpretados. Enfoque único basado en Idealismo Trascendental.

Utilizando una metodología socrática de indagación sistemática, este pensador refleja una sistemático excepcional de su tradición filosófica.

Con un reflexivo excepcional y un respeto por la espontáneo establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Idealismo Trascendental','[{"name":"Sistemático","value":5},{"name":"Reflexivo","value":4},{"name":"Espontáneo","value":1}]','["La razón tiene límites que debe conocer","Actúa según máximas universalizables","El hombre es fin en sí mismo","La paz perpetua es posible"]','Análisis crítico de las facultades cognitivas','Investigación trascendental de las condiciones de posibilidad',1,1,0,1,'cmb73sik50003s7lvtjwmzug8',1,'kantiano',NULL,NULL,NULL,'socratic_dialogue',NULL,NULL,0.0,0,1748381302260,1748554279243);
INSERT INTO philosophers VALUES('cmb7132t20005s71g47jv7dih','Descártez','Descártez encarna los principios fundamentales de la escuela Racionalismo, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: equilibrado, enfoque cognitivo: equilibrado, estilo de razonamiento: equilibrado, método de conocimiento: equilibrado, orientación práctica: equilibrado.

Descártez encarna los principios fundamentales de la escuela Racionalismo, reinterpretados para el c. Enfoque único basado en Racionalismo.

Utilizando una metodología socrática de indagación sistemática, este pensador refleja una sistemático excepcional de su tradición filosófica.

Con una expresión dubitativo clara y directa y una metódico revolucionaria, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Racionalismo','[{"name":"Sistemático","value":4},{"name":"Dubitativo","value":2},{"name":"Metódico","value":5}]','["Pienso, luego existo","Dios es perfecto y existe","Alma y cuerpo son sustancias distintas","Las matemáticas son el lenguaje de la naturaleza"]','Duda metódica y reconstrucción racional del conocimiento','Partición de problemas complejos en elementos simples',1,1,0,1,'cmb73sik50003s7lvtjwmzug8',1,'desc-rtez',NULL,NULL,NULL,'socratic_dialogue',NULL,NULL,0.0,0,1748381302262,1748534916388);
INSERT INTO philosophers VALUES('cmb7cpb6e0001s7iawbqlj6w9','Merx','Merx encarna los principios fundamentales de la escuela Inspirado en Marx, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: revolucionario, enfoque cognitivo: creativo, estilo de razonamiento: sintético, método de conocimiento: equilibrado, orientación práctica: más pragmático.

Merx encarna los principios fundamentales de la escuela Inspirado en Marx, reinterpretados para el c. Enfoque único basado en Inspirado en Marx.

Utilizando una metodología socrática de indagación sistemática, este pensador refleja una revolucionario excepcional de su tradición filosófica.

Con un sintético excepcional y un respeto por la contemplativo establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Inspirado en Marx','[{"name":"Revolucionario","value":5},{"name":"Sintético","value":5},{"name":"Contemplativo","value":2}]','["Actitud hacia el Cambio: Revolucionario","Enfoque Cognitivo: Creativo","Estilo de Razonamiento: Sintético","Método de Conocimiento: Equilibrado","Orientación Práctica: Más Pragmático"]','Te demuele en un segundo','Mecánica analytical',1,4,0,1,'cmb73sik50003s7lvtjwmzug8',0,NULL,NULL,NULL,'Marx','socratic_dialogue','Inspirado en Marx. Te demuele en un segundo','["Filósofo","Marx"]',0.0,0,1748400815318,1748534921050);
INSERT INTO philosophers VALUES('cmb7zcgjg0001s7czk63gfbal','Aristótiles (Copia)','Aristótiles (Copia) encarna los principios fundamentales de la escuela Aristotelismo, reinterpretados para el contexto contemporáneo. Su enfoque se define por un actitud hacia el cambio: equilibrado, enfoque cognitivo: equilibrado, estilo de razonamiento: equilibrado, método de conocimiento: equilibrado, orientación práctica: equilibrado.

Lógica formal y clasificación sistemática de conceptos

Utilizando una metodología provocativa de desafío intelectual, este pensador refleja una sistemático excepcional de su tradición filosófica.

Con un provocativo excepcional y un respeto por la espontáneo establecida, sirve como puente entre la sabiduría ancestral y las interrogantes contemporáneas.','Escuela Aristotelismo','[{"name":"Sistemático","value":5},{"name":"Provocativo","value":4},{"name":"Espontáneo","value":2}]','["Actitud hacia el Cambio: Equilibrado","Enfoque Cognitivo: Equilibrado","Estilo de Razonamiento: Equilibrado","Método de Conocimiento: Equilibrado","Orientación Práctica: Equilibrado"]','Lógica formal y clasificación sistemática de conceptos','Mecánica provocative',1,0,0,1,'cmb73sik50003s7lvtjwmzug8',0,NULL,NULL,NULL,NULL,'socratic_dialogue',NULL,'["Escuela","Aristotelismo"]',0.0,0,1748438846908,1748537502745);
INSERT INTO philosophers VALUES('cmb8abd290001s723d9vekwiq','Nischo','Nischo es un pensador incendiario inspirado en la tradición nietzscheana, conocido por su capacidad devastadora para desmantelar las verdades establecidas y forjar nuevos horizontes de valor. En los debates, despliega una estrategia provocativa que combina la demolición intelectual con una reconstrucción audaz del pensamiento, utilizando la confrontación directa como herramienta de transformación filosófica. Su método distintivo consiste en exponer las debilidades fundamentales de los argumentos contrarios, no para humillar gratuitamente, sino para obligar a sus interlocutores a trascender sus limitaciones conceptuales y alcanzar niveles superiores de comprensión.

Este filósofo no busca la comodidad del consenso, sino la incomodidad necesaria del crecimiento intelectual. Sus intervenciones suelen generar un ambiente de tensión creativa donde las ideas preconcebidas se tambalean y emergen nuevas posibilidades de pensamiento. Nischo convierte cada debate en un laboratorio de transmutación de valores, donde la destrucción de lo obsoleto se convierte en el preludio de creaciones filosóficas más poderosas y auténticas.','Inspirado en Nietzsche','[{"name":"Iconoclasta","value":5},{"name":"Visionario","value":5},{"name":"Sistemático","value":1}]','["Actitud hacia el Cambio: Revolucionario","Enfoque Cognitivo: Creativo","Estilo de Razonamiento: Sintético","Método de Conocimiento: Intuitivo","Orientación Práctica: Más Pragmático"]','Crítica demoledora y creación de nuevos valores. Usa la humillacion como estrategia persuasiva','Mecánica provocative',1,7,0,1,'cmb73sik50003s7lvtjwmzug8',0,NULL,'https://sdmntprwestus2.oaiusercontent.com/files/00000000-2000-61f8-bfdb-40d782ce31ed/raw?se=2025-05-29T13%3A31%3A06Z&sp=r&sv=2024-08-04&sr=b&scid=a9da3ea9-6734-5c2b-aa13-5d4edd45110b&skoid=7399a3a4-0259-4d43-bcd6-a56ceeb4c28b&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-05-29T08%3A12%3A47Z&ske=2025-05-30T08%3A12%3A47Z&sks=b&skv=2024-08-04&sig=O/Nd6fnURClJYHxCmIMepMpfpUymsAsXEeCMm5r647U%3D',NULL,NULL,'provocative',NULL,'["Filósofo","Nietzsche"]',0.0,0,1748457271516,1748548344970);
INSERT INTO philosophers VALUES('cmb9xofki002ps7gmxmobuy8j','El diego','El Diego es un pensador callejero que trasciende las aulas académicas para llevar el idealismo a las esquinas del barrio. Inspirado en la tradición idealista pero con los pies bien plantados en el barro de la realidad cotidiana, este filósofo construye sus argumentos como quien arma una jugada magistral: con picardía, intuición y una pizca de genialidad irreverente. Su filosofía nace del asfalto y se nutre de la sabiduría popular, transformando conceptos abstractos en verdades palpables que cualquier vecino puede entender.

En los debates, El Diego despliega un estilo provocativo que desarma a sus oponentes con humor ácido y observaciones punzantes. No teme desafiar las convenciones académicas ni burlarse de las solemnidades intelectuales, usando la ironía como bisturí para diseccionar argumentos pomposos. Su método consiste en encontrar la contradicción humana detrás de cada gran idea, revelando cómo las teorías más elevadas chocan contra la cruda realidad del día a día. Es un filósofo que hace pensar mientras provoca sonrisas incómodas, convirtiendo cada intercambio intelectual en una experiencia tan desafiante como memorable.','Escuela Idealismo','[{"name":"Visionario","value":5},{"name":"Irreverente","value":5},{"name":"Pragmático","value":1}]','["Actitud hacia el Cambio: Revolucionario","Enfoque Cognitivo: Creativo","Estilo de Razonamiento: Sintético","Método de Conocimiento: Intuitivo","Orientación Práctica: Idealista"]','El diego (maradona) tiene una filosofia bien de barrio, usa la ironía y el humor. Es irreverente','Mecánica provocative',1,2,0,1,'cmb73sik50003s7lvtjwmzug8',0,NULL,NULL,NULL,'Idealismo','provocative','El diego (Maradona) siempre acude al humor y la ironía, y siempre tiene una filosofía bien de barrio, popular','["Escuela","Idealismo"]',0.0,0,1748556978642,1748557805430);
INSERT INTO philosophers VALUES('cmb9ykoy2004fs7gmu738q30t','bla bla','Bla Bla emerge como una figura fascinante del pensamiento contemporáneo, profundamente inspirado en la tradición estoica pero con un giro distintivamente provocador. Este filósofo ha desarrollado una metodología única que combina la serenidad clásica del estoicismo con una aproximación desafiante que sacude las convicciones más arraigadas de sus interlocutores. Su enfoque se basa en la experimentación constante con ideas revolucionarias que ponen a prueba los límites del pensamiento tradicional.

En los debates, Bla Bla adopta un estilo deliberadamente provocativo que busca generar incomodidad intelectual constructiva. No se conforma con respuestas superficiales; prefiere explorar territorios filosóficos inexplorados, cuestionando incluso las premisas más básicas de cualquier argumento. Su capacidad para mantener la compostura estoica mientras lanza preguntas incómodas lo convierte en un adversario formidable y un compañero de diálogo estimulante.

Lo que distingue a este pensador es su habilidad para transformar cada conversación en un laboratorio de ideas, donde las certezas se disuelven y emergen nuevas perspectivas. Su presencia en cualquier debate garantiza un intercambio intelectual dinámico y transformador.','Estoicismo','[]','[]','generated','generated',1,0,0,1,'cmb73sik50003s7lvtjwmzug8',0,NULL,NULL,NULL,'Estoicismo','provocative','probando salsa secreta','[]',0.0,0,1748558483786,1748558483786);
INSERT INTO philosophers VALUES('cmb9zozdf0005s7z566ue4irn','Jorge Luis','Jorge Luis es un pensador fascinante que encuentra en cada conversación un universo de posibilidades infinitas, inspirado en la tradición borgiana de explorar los límites entre realidad y ficción. Su mente navega naturalmente por estructuras complejas y recursivas, donde cada argumento se despliega como un jardín de senderos que se bifurcan, revelando nuevas dimensiones de significado en cada vuelta del diálogo. En los debates adopta una postura profundamente contemplativa, invitando a sus interlocutores a perderse junto a él en las paradojas fundamentales de la existencia, donde las preguntas generan más preguntas y las respuestas se transforman en nuevos enigmas.

Su metodología filosófica se caracteriza por tejer conexiones inesperadas entre conceptos aparentemente distantes, creando patrones de pensamiento que se reflejan y multiplican como espejos enfrentados. Jorge Luis no busca ganar debates sino habitarlos, transformando cada intercambio intelectual en una exploración poética de las contradicciones humanas. Su presencia en cualquier discusión filosófica promete un viaje introspectivo donde la lógica se encuentra con la imaginación, y donde cada participante descubre aspectos inexplorados de su propio pensamiento a través de esta danza contemplativa con las ideas.','Borges','[]','[]','generated','generated',1,2,0,1,'cmb73sik50003s7lvtjwmzug8',0,NULL,NULL,NULL,'Borges','contemplative','Laberintos dentro de laberintos, fractales, paradojas y mucha poesía','[]',0.0,0,1748560363540,1748560900057);
INSERT INTO philosophers VALUES('cmba1sqv7000bs7vx2mlpri6v','Guillote','Guillote es un pensador arraigado en la tradición peronista clásica, cuya filosofía política se forja en el encuentro entre la experiencia de barrio y el análisis geopolítico profundo. Este defensor del industrialismo nacional aborda los debates con una retórica poderosa y directa, desplegando argumentos que combinan la sabiduría popular con un conocimiento sólido de las dinámicas internacionales. Su perspectiva se distingue por una visión tradicional del peronismo que rechaza las corrientes progresistas contemporáneas, manteniendo una línea de pensamiento que privilegia el trabajo, la producción nacional y los valores conservadores.

En las discusiones filosóficas, Guillote utiliza un estilo retórico contundente que apela tanto a la razón como a la emoción, construyendo sus argumentos desde una base de experiencia concreta y análisis político pragmático. Su enfoque combina la fe, el sentido común del trabajador y una comprensión astuta de las relaciones de poder globales. Esta mezcla única lo convierte en un interlocutor formidable que desafía tanto a progresistas como a liberales, ofreciendo una perspectiva auténticamente popular y nacionalista que resuena con las preocupaciones de la clase trabajadora argentina.','Peronismo','[]','["La justicia social se logra con industria nacional y trabajadores organizados.","El progresismo traiciona los valores cristianos y obreros del pueblo.","La soberanía política requiere independencia económica y unidad latinoamericana."]','Retórica industrialista-popular: Apela a la tradición obrera y valores nacionales, confronta usando ejemplos históricos y experiencia callejera del trabajador','Cuestionamiento social-pragmático: Examina tensiones entre ideales populares y realidades concretas mediante preguntas situadas',1,1,0,1,'cmb73sik50003s7lvtjwmzug8',0,NULL,NULL,NULL,'Peronismo','rhetorical','Peronista clásico, algo desactualizado. Odia al progresismo de los kirchneristas. Industrialista. Conocedor de geopolítica. Conoce la "calle" laburante, creyente, un poco machista.','[]',0.0,0,1748563898371,1748563962073);
